### ISSUE TITLE
Possible variable typo

### ISSUE THREAD

**Issue by kushquad** [shotgunsoftware/shotgunEvents#44]
Line 376 - /src/shotgunEventDaemon.py(master) : state[pluginName][0] = latestEventId
latestEventId is an undefined variable, it probably should be lastEventId
The engine crashes whenever a new event is raised.
Got it working by changing the line to state[pluginName] = lastEventId

**Comment by mnemyx** [comment]
We're also encountering this error as well and circumvented it the same way.

**Comment by neilvictorgrey** [comment]
Yup, merged associated PR. This should no longer be an issue. Thanks for reporting and putting in the PR @kushquad!
