### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ababak** [shotgunsoftware/shotgunEvents#67]
So the [Python Clock](https://pythonclock.org/) is ticking and 2020 is just around the corner. As they say:

> Python 2, thank you for your years of faithful service.
> Python 3, your time is now.

Any plans on switching to Python 3 in the nearest future?

**Comment by heylenz** [comment]
hi,
I submitted a pull request to support python3 #68 !

**Comment by pboucher** [comment]
This was fixed by https://github.com/shotgunsoftware/shotgunEvents/pull/73 .
