### ISSUE TITLE
invalid python version number '2.7.15+'

### ISSUE THREAD

**Issue by geoffroygivry** [shotgunsoftware/shotgunEvents#69]
Hi all, when I try to run the command
```
python shotgunEventDaemon.py start
```
I have an error because of the actual version of python which is 2.7.15+.
I assume this is because of this specific version formatting with the '+' at the end.
```
Traceback (most recent call last):
  File "shotgunEventDaemon.py", line 60, in <module>
    CURRENT_PYTHON_VERSION = StrictVersion(sys.version.split()[0])
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '2.7.15+'
```
Is there any workaround to get this working?
Thank you for your answer.

**Comment by pscadding** [comment]
What does `sys.version.split()[0]` return for you is that `2.7.15+`?
As a workaround you can modify [this line](https://github.com/shotgunsoftware/shotgunEvents/blob/d246d02810cb5311cc25739901894e933fa3df73/src/shotgunEventDaemon.py#L60) to be 
```python
CURRENT_PYTHON_VERSION = StrictVersion("2.7.15")
```
And I think that would work.

**Comment by geoffroygivry** [comment]
Hi Philip, 
Many thanks for your reply.
That definitely works! thank you so much for this.

I am closing this issue as you've resolved it.
Cheers!
Geoff
