### ISSUE TITLE
ValueError: can’t have unbuffered text I/O

### ISSUE THREAD

**Issue by kvnlmr** [shotgunsoftware/shotgunEvents#76]
We are implementing ShotgunEventDaemon for some systematic task.
It runs perfectly when run in Foreground but I’m unable to launch it in background using the start argument.
Here’s the error I get:

```
[ws] user ~ >python3 /prod/studio/libs/python/3.6/linux/site-packages/shotgunEvents/src/shotgunEventDaemon.py start
Traceback (most recent call last):
File “/prod/studio/libs/python/3.6/linux/site-packages/shotgunEvents/src/shotgunEventDaemon.py”, line 1418, in
sys.exit(main())
File “/prod/studio/libs/python/3.6/linux/site-packages/shotgunEvents/src/shotgunEventDaemon.py”, line 1382, in main
func()
File “/prod/studio/libs/python/3.6/linux/site-packages/shotgunEvents/src/shotgunEventDaemon.py”, line 1353, in start
super(LinuxDaemon, self).start(daemonize)
File “/prod/studio/libs/python/3.6/linux/site-packages/shotgunEvents/src/daemonizer.py”, line 115, in start
self._daemonize()
File “/prod/studio/libs/python/3.6/linux/site-packages/shotgunEvents/src/daemonizer.py”, line 74, in _daemonize
se = open(self._stderr, “a+”, 0)
ValueError: can’t have unbuffered text I/O
```

Any clue on what could cause this error? Thank!

**Comment by Jazielinc** [comment]
im running on python 2.7 and no problem but you are using python 3 so i think you can see this answer on stackOverflow:

https://stackoverflow.com/questions/45263064/how-can-i-fix-this-valueerror-cant-have-unbuffered-text-i-o-in-python-3/45263101

**Comment by kvnlmr** [comment]
I've already tried this without success. 
I've opened a ticket with Shotgun Software to figure this out.

**Comment by Jazielinc** [comment]
Just to say that i did the test on python3 and i get the same error but i did the change on the line 74 of demonizer.py
from 
`se = open(self._stderr, "a+", 0) `
to 
`se = open(self._stderr, "a+")`

and it worked fine.

**Comment by kvnlmr** [comment]
Thank you @Jazielinc, it did the trick!
